version: '2'

services:

  postgres:
    image: postgres
    volumes:
      - ./data/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monitor

  redis:
    image: redis

  monitor:
    build: .
    ports:
      - 8080:8080
    command: monitor
    depends_on:
      - postgres
      - redis
    environment:
      - PORT=8080
      - DB_URL=postgres://postgres:postgres@postgres:5432/monitor?sslmode=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1
      - SMTP_HOST=smtp.yandex.ru
      - SMTP_PORT=587
      - SMTP_LOGIN=dmetric@yandex.ru
      - SMTP_PASSWORD=Dmetric.
      - MAIL_TO=dmetric@yandex.ru
      - METRIC1_MIN=0
      - METRIC1_MAX=10
      - METRIC2_MIN=0
      - METRIC2_MAX=10
      - METRIC3_MIN=0
      - METRIC3_MAX=10
      - METRIC4_MIN=0
      - METRIC4_MAX=10
      - METRIC5_MIN=0
      - METRIC5_MAX=10